name: 'Silver Bullet: Prometheus'
slug: silver-bullet-prometheus
year: null
platforms: []
genres: []
aliases: []
banner_url: /games/banner/silver-bullet-prometheus.jpg
icon_url: /games/icon/silver-bullet-prometheus.png
is_public: false
updated: '2019-01-23T08:31:13.613813Z'
steamid: 446250
gogslug: ''
humblestoreid: ''
