id: 14392
game_id: 14218
game_slug: train-sim-world-csx-heavy-haul
name: Train Sim World
year: 2018
user: tfk
runner: steam
slug: train-sim-world-steam-proton
version: Steam Proton
description: null
notes: ''
created_at: '2019-07-02T22:17:13.907000Z'
updated_at: '2019-11-04T04:49:06.919288Z'
draft: false
published: true
published_by: 19464
rating: ''
steamid: 530070
gogid: null
gogslug: ''
humblestoreid: ''
script:
  game:
    appid: 530070
